version: '3.8'
services:
  db:
    image: postgres:14
    container_name: ammamas-kitchen-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: ammamas_db
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ammamas_user -d ammamas_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
      
  maildev:
    image: maildev/maildev
    container_name: ammamas-kitchen-maildev
    ports:
      - "1081:1080"  # Web interface
      - "1026:1025"  # SMTP server
    environment:
      - MAILDEV_WEB_USER=dev    # Optional: Basic auth username
      - MAILDEV_WEB_PASS=dev    # Optional: Basic auth password
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: